#----------------Dir_settings:----------------------------------------------
base_dir: /mnt/data/CREMCOMICSdo001/dsobral/vcall/ #where it start in docker env
main_dir: /mnt/data/CREMCOMICSdo001/dsobral/vcall/
genome_dir: genome_b37/ # genome data
sample_dir: sample_input/ #sample directory
output_dir: output/ #output folder
logs_dir: logs/ # for logs...

#---------------Settings:----------------------------------------------
GENOME: b37_human_g1k_v37_decoy.chr20
KS1: b37_dbsnp_138.b37.chr_20p12.1.vcf.gz
KS2: b37_Mills_and_1000G_gold_standard.indels.b37.chr_20p12.1.vcf.gz
KS3: b37_1000G_phase1.indels.b37.chr_20p12.1.vcf.gz
#KS -> KnowSites

TARGET: -L /mnt/data/CREMCOMICSdo001/dsobral/vcall/sample_input/b37.vcrome2.1.ann.chr_20.bed
TARGET_C: --targets /mnt/data/CREMCOMICSdo001/dsobral/vcall/sample_input/b37.vcrome2.1.ann.chr_20.bed
#TARGET: ""
COSMIC: --cosmic /mnt/data/CREMCOMICSdo001/dsobral/vcall/genome_b37/CosmicCodingMuts_v87_12_03_2019.chr_20p12.1.vcf.gz
#COSMIC: ""

#___________________________Threading_______________________:
BWA_samblaster_sambamba_threads: 4 
GATK_baserecalibrator_threads: 4
GATK_applyrecalibration_threads: 4
Call_Variants_threads: 4
Normal_VS_Tumor_threads: 4
