#----------------Dir_settings:----------------------------------------------
main_dir: /mnt/data/CREMCOMICSdo001/dsobral/vcall/
genome_dir: /mnt/data/CREMCOMICSdo001/comics/genome/hg38/
sample_dir: sample_input/ #sample director, where samples are (relative to main_dir)
output_dir: output/ #output folder (relative to main_dir)

#---------------Settings:----------------------------------------------
GENOME: resources_broad_hg38_v0_Homo_sapiens_assembly38
KS1: resources_broad_hg38_v0_Homo_sapiens_assembly38.dbsnp138.vcf.gz
KS2: resources_broad_hg38_v0_Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
KS3: resources_broad_hg38_v0_Homo_sapiens_assembly38.known_indels.vcf.gz
#KS -> KnowSites

TARGET: -L /mnt/data/CREMCOMICSdo001/comics/genome/hg38/S07604514_Covered.bed
TARGET_C: --targets /mnt/data/CREMCOMICSdo001/comics/genome/hg38/S07604514_Covered.bed
#TARGET: ""
#TARGET_C: ""
COSMIC: --cosmic /mnt/data/CREMCOMICSdo001/comics/genome/hg38/CosmicCodingMuts.hg38.vcf.gz
#COSMIC: ""

#___________________________Threading_______________________:
BWA_samblaster_sambamba_threads: 4 
GATK_baserecalibrator_threads: 4
GATK_applyrecalibration_threads: 4
Call_Variants_threads: 4
Normal_VS_Tumor_threads: 4
